import { PROJECT_THUMBNAILS } from '../constants';
import type { ProjectProps } from '../models';

export const Projects: ProjectProps[] = [
  {
    ...PROJECT_THUMBNAILS.LA_BRAVA,
    title: 'La Brava CSR',
    role: 'Sole Engineer',
    techs: [
      { tech: 'REACT', version: '18.3.1' },
      { tech: 'REACT_NATIVE', version: '0.76.9' },
      { tech: 'TYPESCRIPT', version: '5.3.3' },
      { tech: 'EXPO', version: '52.0.44' },
      { tech: 'WATERMELONDB', version: '0.28.0' },
      { tech: 'JEST', version: '29.2.1' },
    ],
  },
  {
    ...PROJECT_THUMBNAILS.ZEST,
    title: 'Zest Partner Program',
    role: 'React Native Team Lead',
    techs: [
      { tech: 'REACT', version: '17.0.2' },
      { tech: 'REACT_NATIVE', version: '0.69.0' },
      { tech: 'TYPESCRIPT', version: '4.7.4' },
      { tech: 'EXPO', version: '45.0.0' },
      { tech: 'ZUSTAND', version: '3.7.1' },
      { tech: 'JEST', version: '28.1.0' },
    ],
  },
  {
    ...PROJECT_THUMBNAILS.CHANEL,
    title: 'Chanel Beauty Atelier',
    role: 'React Native Developer',
    techs: [
      { tech: 'REACT', version: '17.0.2' },
      { tech: 'REACT_NATIVE', version: '0.67.2' },
      { tech: 'TYPESCRIPT', version: '4.5.5' },
      { tech: 'EXPO', version: '44.0.0' },
      { tech: 'ZUSTAND', version: '3.7.1' },
      { tech: 'JEST', version: '27.5.1' },
      { tech: 'DETOX', version: '19.8.0' },
    ],
  },
  {
    ...PROJECT_THUMBNAILS.DOLBY,
    title: 'Dolby XP - HUB',
    role: 'React Native Developer',
    techs: [
      { tech: 'REACT', version: '17.0.2' },
      { tech: 'REACT_NATIVE', version: '0.66.5' },
      { tech: 'TYPESCRIPT', version: '4.4.4' },
      { tech: 'FIREBASE', version: '12.6.1' },
      { tech: 'MOBX', version: '2.2.2' },
      { tech: 'JEST', version: '26.3.0' },
      { tech: 'STYLED_COMPONENTS', version: '5.3.0' },
      { tech: 'OKTA', version: '2.6.0' },
    ],
  },
  {
    ...PROJECT_THUMBNAILS.THREE43,
    title: 'Three43',
    role: 'React Native Developer',
    techs: [
      { tech: 'REACT', version: '16.9.0' },
      { tech: 'REACT_NATIVE', version: '0.61.2' },
      { tech: 'TYPESCRIPT', version: '3.6.3' },
      { tech: 'GRAPHQL', version: '14.5.7' },
      { tech: 'APOLLO', version: '2.6.8' },
      { tech: 'FIREBASE', version: '6.2.0' },
      { tech: 'JEST', version: '24.9.0' },
      { tech: 'STYLED_COMPONENTS', version: '4.4.0' },
    ],
  },
  {
    ...PROJECT_THUMBNAILS.MOTORCULTURE,
    title: 'Motorculture',
    role: 'React Native Developer',
    techs: [
      { tech: 'REACT', version: '16.8.6' },
      { tech: 'REACT_NATIVE', version: '0.59.9' },
      { tech: 'REACT_NATIVE_NAV', version: '2.0.26' },
      { tech: 'REDUX', version: '4.0.1' },
      { tech: 'SENTRY', version: '0.43.1' },
      { tech: 'FIREBASE', version: '6.2.0' },
      { tech: 'JEST', version: '24.8.0' },
    ],
  },
  {
    ...PROJECT_THUMBNAILS.VIGIT,
    title: 'Vigit',
    role: 'React Native Developer',
    techs: [
      { tech: 'REACT', version: '16.8.4' },
      { tech: 'REACT_NATIVE', version: '0.59.5' },
      { tech: 'TYPESCRIPT', version: '3.5.3' },
      { tech: 'REDUX', version: '4.0.1' },
      { tech: 'EXPO', version: '33.0.0' },
      { tech: 'JEST', version: '24.7.0' },
      { tech: 'STRIPE', version: '7.9.0' },
      { tech: 'FIREBASE', version: '6.2.0' },
    ],
  },
  {
    ...PROJECT_THUMBNAILS.COSMO,
    title: 'Cosmo',
    role: 'React Native Developer',
    techs: [
      { tech: 'REACT', version: '16.8.0' },
      { tech: 'REACT_NATIVE', version: '0.58.6' },
      { tech: 'REDUX', version: '4.0.1' },
      { tech: 'JEST', version: '24.1.0' },
      { tech: 'SENTRY', version: '0.43.1' },
    ],
  },
  {
    ...PROJECT_THUMBNAILS.DARE_YOU,
    title: 'Dar You',
    role: 'React Native Developer',
    techs: [
      { tech: 'REACT', version: '16.7.0' },
      { tech: 'REACT_NATIVE', version: '0.58.4' },
      { tech: 'REACT_NATIVE_NAV', version: '1.1.4' },
      { tech: 'REDUX', version: '4.0.0' },
      { tech: 'JEST', version: '24.1.0' },
    ],
  },
  {
    ...PROJECT_THUMBNAILS.SAIPROP,
    title: 'Saiprop',
    role: 'React Native Developer',
    techs: [
      { tech: 'REACT', version: '16.8.1' },
      { tech: 'REACT_NATIVE', version: '0.58.5' },
      { tech: 'REACT_NATIVE_NAV', version: '1.1.4' },
      { tech: 'REDUX', version: '4.0.0' },
      { tech: 'JEST', version: '24.0.0' },
    ],
  },
  {
    ...PROJECT_THUMBNAILS.DROPDESK,
    title: 'Dropdesk',
    role: 'React Native Developer',
    techs: [
      { tech: 'REACT', version: '16.6.3' },
      { tech: 'REACT_NATIVE', version: '0.57.8' },
      { tech: 'EXPO', version: '32.0.0' },
      { tech: 'REDUX', version: '4.0.0' },
      { tech: 'REACT_NATIVE_NAV', version: '2.0.26' },
    ],
  },
  {
    ...PROJECT_THUMBNAILS.INGAGEDIN,
    title: 'Ingagedin',
    role: 'React Native Developer',
    techs: [
      { tech: 'REACT', version: '16.6.3' },
      { tech: 'REACT_NATIVE', version: '0.57.8' },
      { tech: 'EXPO', version: '32.0.0' },
      { tech: 'REDUX', version: '4.0.0' },
      { tech: 'JEST', version: '23.6.0' },
    ],
  },
  {
    ...PROJECT_THUMBNAILS.ACCOMPLISH,
    title: 'Now Accomplish',
    role: 'React Native Developer',
    techs: [
      { tech: 'REACT', version: '16.6.0' },
      { tech: 'REACT_NATIVE', version: '0.57.8' },
      { tech: 'REDUX', version: '4.0.0' },
      { tech: 'EXPO', version: '32.0.0' },
    ],
  },
  {
    ...PROJECT_THUMBNAILS.POLLAPP,
    title: 'Pollap',
    role: 'React Native Developer',
    techs: [
      { tech: 'REACT', version: '16.4.1' },
      { tech: 'REACT_NATIVE', version: '0.56.0' },
      { tech: 'REDUX', version: '4.0.0' },
      { tech: 'FIREBASE', version: '5.5.0' },
      { tech: 'JEST', version: '23.6.0' },
    ],
  },
  {
    ...PROJECT_THUMBNAILS.EVERWASH,
    title: 'Everwash',
    role: 'React Native Developer',
    techs: [
      { tech: 'REACT', version: '16.4.1' },
      { tech: 'REACT_NATIVE', version: '0.56.0' },
      { tech: 'REDUX', version: '4.0.0' },
      { tech: 'JEST', version: '23.6.0' },
    ],
  },
  {
    ...PROJECT_THUMBNAILS.APLACASH,
    title: 'AplaCash',
    role: 'React Native Developer',
    techs: [
      { tech: 'REACT', version: '16.3.0' },
      { tech: 'REACT_NATIVE', version: '0.55.4' },
      { tech: 'EXPO', version: '27.0.0' },
      { tech: 'REDUX', version: '4.0.0' },
      { tech: 'LOTTIE', version: '2.5.0' },
      { tech: 'REACT_NATIVE_NAV', version: '2.0.0' },
    ],
  },
  {
    ...PROJECT_THUMBNAILS.HOLCIM,
    title: 'Holcim H&S',
    role: 'React Native Developer',
    techs: [
      { tech: 'REACT', version: '16.3.0' },
      { tech: 'REACT_NATIVE', version: '0.55.4' },
      { tech: 'REDUX', version: '4.0.0' },
      { tech: 'REACT_NATIVE_NAV', version: '2.0.0' },
      { tech: 'JEST', version: '22.4.3' },
    ],
  },
];
