export const MOCK_GRID_ITEMS = [
  {
    id: '1',
    iconPath: '/reactnative.svg',
    iconAltText: 'React Native',
    iconLink: '#',
    shadowColor: '#61dafb',
    className: 'reactnative',
    title: 'React Native',
    description: 'Framework para apps móviles.',
  },
  {
    id: '2',
    iconPath: '/redux.svg',
    iconAltText: 'Redux',
    iconLink: '#',
    shadowColor: '#764abc',
    className: 'redux',
    title: 'Redux',
    description: 'Gestión de estado predecible.',
  },
  {
    id: '3',
    iconPath: '/typescript.svg',
    iconAltText: 'TypeScript',
    iconLink: '#',
    shadowColor: '#3178c6',
    className: 'typescript',
    title: 'TypeScript',
    description: 'Superset de JavaScript tipado.',
  },
  {
    id: '4',
    iconPath: '/vite.svg',
    iconAltText: 'Vite',
    iconLink: '#',
    shadowColor: '#646cff',
    className: 'vite',
    title: 'Vite',
    description: 'Herramienta de build rápida.',
  },
  {
    id: '5',
    iconPath: '/javascript.svg',
    iconAltText: 'JavaScript',
    iconLink: '#',
    shadowColor: '#f7df1e',
    className: 'javascript',
    title: 'JavaScript',
    description: 'Lenguaje de la web.',
  },
  {
    id: '6',
    iconPath: '/expo.svg',
    iconAltText: 'Expo',
    iconLink: '#',
    shadowColor: '#000020',
    className: 'expo',
    title: 'Expo',
    description: 'Herramienta para apps React Native.',
  },
  {
    id: '7',
    iconPath: '/location.svg',
    iconAltText: 'Location',
    iconLink: '#',
    shadowColor: '#e53e3e',
    className: 'location',
    title: 'Location',
    description: 'Servicios de geolocalización.',
  },
  {
    id: '8',
    iconPath: '/linkedin.svg',
    iconAltText: 'LinkedIn',
    iconLink: '#',
    shadowColor: '#0077b5',
    className: 'linkedin',
    title: 'LinkedIn',
    description: 'Red profesional.',
  },
  {
    id: '9',
    iconPath: '/typescript.svg',
    iconAltText: 'Mail',
    iconLink: '#',
    shadowColor: '#ea4335',
    className: 'mail',
    title: 'Mail',
    description: 'Comunicación por correo.',
  },
  {
    id: '10',
    iconPath: '/menu_b.svg',
    iconAltText: 'Menu',
    iconLink: '#',
    shadowColor: '#333333',
    className: 'menu_b',
    title: 'Menú',
    description: 'Navegación principal.',
  },
  {
    id: '11',
    iconPath: '/typescript.svg',
    iconAltText: 'Menu White',
    iconLink: '#',
    shadowColor: '#ffffff',
    className: 'menu_w',
    title: 'Menú Blanco',
    description: 'Navegación alternativa.',
  },
  {
    id: '12',
    iconPath: '/x_b.svg',
    iconAltText: 'X Black',
    iconLink: '#',
    shadowColor: '#000000',
    className: 'x_b',
    title: 'X Black',
    description: 'Ícono X negro.',
  },
  {
    id: '13',
    iconPath: '/typescript.svg',
    iconAltText: 'X White',
    iconLink: '#',
    shadowColor: '#000000',
    className: 'x_w',
    title: 'X White',
    description: 'Ícono X blanco.',
  },
];
