import type { TECHNOLOGIES_DATA_TYPE } from './utils';

export type ProjectItemType = TECHNOLOGIES_DATA_TYPE[string] & {
  id: string;
  title: string;
  description: string;
  className: string;
};

export const PROJECTS_LIST: ProjectItemType[] = [
  {
    id: '1',
    thumbnailPath:
      'https://ik.imagekit.io/kd907zpil/portfolio_assets/projects_thumbnails/1.webp?updatedAt=1751504953258',
    thumbnailAltText: 'React Native',
    thumbnailLink: '#',
    shadowColor: '#61dafb',
    className: 'mb-8 h-30 w-30 object-contain rounded-full',
    title: 'React Native',
    description: 'Framework para apps móviles.',
  },
  {
    id: '2',
    thumbnailPath: '/redux.svg',
    thumbnailAltText: 'Redux',
    thumbnailLink: '#',
    shadowColor: '#764abc',
    className: 'mb-8 h-60 w-60 object-contain',
    title: 'Redux',
    description: 'Gestión de estado predecible.',
  },
  {
    id: '3',
    thumbnailPath: '/typescript.svg',
    thumbnailAltText: 'TypeScript',
    thumbnailLink: '#',
    shadowColor: '#3178c6',
    className: 'mb-8 h-60 w-60 object-contain',
    title: 'TypeScript',
    description: 'Superset de JavaScript tipado.',
  },
  {
    id: '4',
    thumbnailPath: '/vite.svg',
    thumbnailAltText: 'Vite',
    thumbnailLink: '#',
    shadowColor: '#646cff',
    className: 'mb-8 h-60 w-60 ',
    title: 'Vite',
    description: 'Herramienta de build rápida.',
  },
  {
    id: '5',
    thumbnailPath: '/javascript.svg',
    thumbnailAltText: 'JavaScript',
    thumbnailLink: '#',
    shadowColor: '#f7df1e',
    className: 'mb-8 h-60 w-60 ',
    title: 'JavaScript',
    description: 'Lenguaje de la web.',
  },
  {
    id: '6',
    thumbnailPath: '/expo.svg',
    thumbnailAltText: 'Expo',
    thumbnailLink: '#',
    shadowColor: '#000020',
    className: 'mb-8 h-60 w-60 ',
    title: 'Expo',
    description: 'Herramienta para apps React Native.',
  },
  {
    id: '7',
    thumbnailPath: '/location.svg',
    thumbnailAltText: 'Location',
    thumbnailLink: '#',
    shadowColor: '#e53e3e',
    className: 'mb-8 h-60 w-60 ',
    title: 'Location',
    description: 'Servicios de geolocalización.',
  },
  {
    id: '8',
    thumbnailPath: '/linkedin.svg',
    thumbnailAltText: 'LinkedIn',
    thumbnailLink: '#',
    shadowColor: '#0077b5',
    className: 'mb-8 h-60 w-60 ',
    title: 'LinkedIn',
    description: 'Red profesional.',
  },
  {
    id: '9',
    thumbnailPath: '/typescript.svg',
    thumbnailAltText: 'Mail',
    thumbnailLink: '#',
    shadowColor: '#ea4335',
    className: 'mb-8 h-60 w-60 ',
    title: 'Mail',
    description: 'Comunicación por correo.',
  },
  {
    id: '10',
    thumbnailPath: '/menu_b.svg',
    thumbnailAltText: 'Menu',
    thumbnailLink: '#',
    shadowColor: '#333333',
    className: 'mb-8 h-60 w-60 ',
    title: 'Menú',
    description: 'Navegación principal.',
  },
  {
    id: '11',
    thumbnailPath: '/typescript.svg',
    thumbnailAltText: 'Menu White',
    thumbnailLink: '#',
    shadowColor: '#ffffff',
    className: 'mb-8 h-60 w-60 ',
    title: 'Menú Blanco',
    description: 'Navegación alternativa.',
  },
  {
    id: '12',
    thumbnailPath: '/x_b.svg',
    thumbnailAltText: 'X Black',
    thumbnailLink: '#',
    shadowColor: '#000000',
    className: 'mb-8 h-60 w-60 object-contain',
    title: 'X Black',
    description: 'Ícono X negro.',
  },
  {
    id: '13',
    thumbnailPath: '/typescript.svg',
    thumbnailAltText: 'X White',
    thumbnailLink: '#',
    shadowColor: '#000000',
    className: 'mb-8 h-60 w-60 ',
    title: 'X White',
    description: 'Ícono X blanco.',
  },
];
